version: '2'

services:
    'pgnode_A': #fyzyS#
        # container_name: pgnode_A
        image: dperetti/pgpilot:node-latest
        ports:
            - "6000:5432"
            - "8888:8888"
        environment:
            - pass=mypassword
        # network_mode: "bridge"

    'pgnode_B':
        # container_name: pgnode_B
        image: dperetti/pgpilot:node-latest
        ports:
            - "6001:5432"
            - "8889:8888"
        environment:
            - pass=mypassword
        # network_mode: "bridge"

    'front':
        # container_name: pgpilot_front
        image: dperetti/pgpilot:front-latest
        # build:
        #   context: pgpilot-webapp
        #   dockerfile: docker/Dockerfile
        ports:
            - "3000:3000"
            - "8080:80"
            - "8081:81"
        environment:
            - CONFIGURATION_DIR=/config
        volumes:
            - .:/config
        links:
            - pgnode_A
            - pgnode_B
        # network_mode: "bridge"
